language: python
python:
  - "3.5"
before_install:
  - mv secrets.example.yaml secrets.yaml
  - sudo apt-get install -y libudev-dev
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
