- id: '1564203487656'
  alias: Start HomeKit
  trigger:
    - platform: event
      event_type: zwave.network_ready
    - platform: event
      event_type: zwave.network_complete
    - platform: event
      event_type: zwave.network_complete_some_dead
  action:
    - delay: 00:02
    - service: homekit.start
